spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password:
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml


